name: mcdota
version: ${project.version}
main: de.prentl.firsttestproject.Main
api-version: 1.13
authors: [Leo, Papa]
description: n/a

commands:
  date:
    description: Zeigt das Datum an
  blueplay:
    description: Spiel im Blauen Team
  yellowplay:
    description: Spiel im Gelben Team
  lobby:
    description: Teleport zur Lobby

