name: mcdota
version: 1.0-SNAPSHOT
main: de.prentl.firsttestproject.McDotaMain
api-version: 1.13
authors: [Leo, Papa]
description: n/a

commands:
  date:
    description: Zeigt das Datum an
  blueplay:
    description: Spiel im Blauen Team
  yellowplay:
    description: Spiel im Gelben Team
  lobby:
    description: Teleport zur Lobby
  mirror:
    description: Die Spielfeldhälfte spiegeln

